import type { Ad, Seller } from './types';

const sellers: Seller[] = [
  {
    id: 'seller-1',
    name: 'Modern Electronics',
    avatarUrl: 'https://picsum.photos/seed/seller1/100/100',
    email: 'contact@modernelectronics.com',
    phone: '+8801712345678',
    whatsapp: '+8801712345678',
    location: 'GEC Circle, Chattogram',
    rating: 4.8,
    reviews: 125,
  },
  {
    id: 'seller-2',
    name: 'Fashion Hub Ctg',
    avatarUrl: 'https://picsum.photos/seed/seller2/100/100',
    email: 'support@fashionhub.com',
    phone: '+8801812345679',
    whatsapp: '+8801812345679',
    location: 'Agrabad, Chattogram',
    rating: 4.5,
    reviews: 88,
  },
  {
    id: 'seller-3',
    name: 'Home Decor BD',
    avatarUrl: 'https://picsum.photos/seed/seller3/100/100',
    email: 'info@homedecorbd.com',
    phone: '+8801912345680',
    whatsapp: '+8801912345680',
    location: 'Hathazari, Chattogram',
    rating: 4.9,
    reviews: 210,
  },
   {
    id: 'seller-4',
    name: 'Gadget Guru',
    avatarUrl: 'https://picsum.photos/seed/seller4/100/100',
    email: 'guru@gadgets.com',
    phone: '+8801612345681',
    whatsapp: '+8801612345681',
    location: 'Patiya, Chattogram',
    rating: 4.7,
    reviews: 95,
  },
  {
    id: 'seller-5',
    name: 'Fresh Fruits Co.',
    avatarUrl: 'https://picsum.photos/seed/seller5/100/100',
    email: 'fresh@fruits.com',
    phone: '+8801512345682',
    whatsapp: '+8801512345682',
    location: 'Boalkhali, Chattogram',
    rating: 4.9,
    reviews: 150,
  },
  {
    id: 'seller-6',
    name: 'Bookworm Library',
    avatarUrl: 'https://picsum.photos/seed/seller6/100/100',
    email: 'books@worm.com',
    phone: '+8801711111111',
    whatsapp: '+8801711111111',
    location: 'Jamalkhan, Chattogram',
    rating: 4.9,
    reviews: 300,
  },
  {
    id: 'seller-7',
    name: 'Kitchen Essentials',
    avatarUrl: 'https://picsum.photos/seed/seller7/100/100',
    email: 'kitchen@essentials.com',
    phone: '+8801822222222',
    whatsapp: '+8801822222222',
    location: 'Chawkbazar, Chattogram',
    rating: 4.7,
    reviews: 180,
  },
  {
    id: 'seller-8',
    name: 'Sports Pro',
    avatarUrl: 'https://picsum.photos/seed/seller8/100/100',
    email: 'pro@sports.com',
    phone: '+8801933333333',
    whatsapp: '+8801933333333',
    location: 'M. A. Aziz Stadium, Chattogram',
    rating: 4.6,
    reviews: 140,
  },
  {
    id: 'seller-9',
    name: 'Green Nursery',
    avatarUrl: 'https://picsum.photos/seed/seller9/100/100',
    email: 'green@nursery.com',
    phone: '+8801644444444',
    whatsapp: '+8801644444444',
    location: 'Foy\'s Lake, Chattogram',
    rating: 4.9,
    reviews: 250,
  },
  {
    id: 'seller-10',
    name: 'Pet Paradise',
    avatarUrl: 'https://picsum.photos/seed/seller10/100/100',
    email: 'pet@paradise.com',
    phone: '+8801555555555',
    whatsapp: '+8801555555555',
    location: 'Nasirabad, Chattogram',
    rating: 4.8,
    reviews: 190,
  },
];

const ads: Ad[] = [
  {
    id: 'ad-1',
    title: 'Brand New 14" Laptop',
    description: 'Latest model with 16GB RAM, 512GB SSD. Perfect for students and professionals. Sealed box with 1 year warranty.',
    price: 85000,
    imageUrl: 'https://picsum.photos/seed/ad1/600/400',
    sellerId: 'seller-1',
    category: 'Electronics',
    location: 'GEC Circle, Chattogram',
  },
  {
    id: 'ad-2',
    title: 'Men\'s Premium Leather Jacket',
    description: '100% genuine leather jacket. Available in M, L, XL sizes. Limited stock available.',
    price: 4500,
    imageUrl: 'https://picsum.photos/seed/ad2/600/400',
    sellerId: 'seller-2',
    category: 'Men\'s Corner',
    location: 'Agrabad, Chattogram',
  },
  {
    id: 'ad-3',
    title: 'Handcrafted Wooden Chair',
    description: 'Elegant and durable wooden chair made from Segun wood. Adds a classic touch to your home.',
    price: 7800,
    imageUrl: 'https://picsum.photos/seed/ad3/600/400',
    sellerId: 'seller-3',
    category: 'Furniture\'s Corner',
    location: 'Hathazari, Chattogram',
  },
  {
    id: 'ad-4',
    title: 'Wireless Bluetooth Headphones',
    description: 'Noise-cancelling headphones with 20 hours of battery life. Crystal clear sound quality.',
    price: 3200,
    imageUrl: 'https://picsum.photos/seed/ad4/600/400',
    sellerId: 'seller-1',
    category: 'Electronics',
    location: 'GEC Circle, Chattogram',
  },
  {
    id: 'ad-5',
    title: 'Designer Women\'s Handbag',
    description: 'A stylish and spacious handbag for every occasion. High-quality synthetic leather.',
    price: 2500,
    imageUrl: 'https://picsum.photos/seed/ad5/600/400',
    sellerId: 'seller-2',
    category: 'Female\'s Corner',
    location: 'Agrabad, Chattogram',
  },
  {
    id: 'ad-6',
    title: 'Minimalist Wall Clock',
    description: 'Modern wall clock, silent movement. Perfect for living room or office. 12-inch diameter.',
    price: 1500,
    imageUrl: 'https://picsum.photos/seed/ad6/600/400',
    sellerId: 'seller-3',
    category: 'Home Decor',
    location: 'Hathazari, Chattogram',
  },
  {
    id: 'ad-7',
    title: 'Gaming Mouse with RGB',
    description: 'High-precision gaming mouse with customizable RGB lighting. 16000 DPI sensor.',
    price: 2800,
    imageUrl: 'https://picsum.photos/seed/ad7/600/400',
    sellerId: 'seller-1',
    category: 'Electronics',
    location: 'Sitakunda, Chattogram',
  },
  {
    id: 'ad-8',
    title: 'Summer Collection T-shirt',
    description: 'Comfortable cotton T-shirt, perfect for summer. Various designs available.',
    price: 800,
    imageUrl: 'https://picsum.photos/seed/ad8/600/400',
    sellerId: 'seller-2',
    category: 'Men\'s Corner',
    location: 'Boalkhali, Chattogram',
  },
  {
    id: 'ad-9',
    title: 'Kids\' Remote Control Car',
    description: 'Fast and durable remote control car for kids. Perfect gift for birthdays. Batteries included.',
    price: 1800,
    imageUrl: 'https://picsum.photos/seed/ad9/600/400',
    sellerId: 'seller-4',
    category: 'Kid\'s Corner',
    location: 'Patiya, Chattogram',
  },
  {
    id: 'ad-10',
    title: 'Organic Apple Box (5kg)',
    description: 'Fresh and juicy organic apples, directly from the farm. Sweet and healthy.',
    price: 1200,
    imageUrl: 'https://picsum.photos/seed/ad10/600/400',
    sellerId: 'seller-5',
    category: 'Fruit\'s Corner',
    location: 'Boalkhali, Chattogram',
  },
  {
    id: 'ad-11',
    title: 'Modern Sofa Set',
    description: '3+2 seater sofa set. Comfortable and stylish. Perfect for modern living rooms. Fabric warranty included.',
    price: 35000,
    imageUrl: 'https://picsum.photos/seed/ad11/600/400',
    sellerId: 'seller-3',
    category: 'Furniture\'s Corner',
    location: 'Hathazari, Chattogram',
  },
  {
    id: 'ad-12',
    title: 'Stylish Women\'s Watch',
    description: 'Elegant and classy watch for women. Stainless steel strap with a beautiful dial.',
    price: 3800,
    imageUrl: 'https://picsum.photos/seed/ad12/600/400',
    sellerId: 'seller-2',
    category: 'Female\'s Corner',
    location: 'Agrabad, Chattogram',
  },
  {
    id: 'ad-13',
    title: 'Smartwatch with Fitness Tracker',
    description: 'Track your steps, heart rate, and more. Connects to your smartphone. Long battery life.',
    price: 4200,
    imageUrl: 'https://picsum.photos/seed/ad13/600/400',
    sellerId: 'seller-4',
    category: 'Gadgets for Men',
    location: 'Patiya, Chattogram',
  },
  {
    id: 'ad-14',
    title: 'Fresh Mango Basket',
    description: 'Delicious and sweet mangoes from our own garden. Handpicked and carefully packed.',
    price: 950,
    imageUrl: 'https://picsum.photos/seed/ad14/600/400',
    sellerId: 'seller-5',
    category: 'Fruit\'s Corner',
    location: 'Boalkhali, Chattogram',
  },
  {
    id: 'ad-15',
    title: 'Baby Stroller',
    description: 'Safe and comfortable stroller for your little one. Easy to fold and carry. Multiple recline positions.',
    price: 6500,
    imageUrl: 'https://picsum.photos/seed/ad15/600/400',
    sellerId: 'seller-4',
    category: 'Kid\'s Corner',
    location: 'Patiya, Chattogram',
  },
  {
    id: 'ad-16',
    title: 'Classic Novel Collection',
    description: 'A collection of 5 classic novels. Includes works by famous authors. Paperback editions.',
    price: 2200,
    imageUrl: 'https://picsum.photos/seed/ad16/600/400',
    sellerId: 'seller-6',
    category: 'Books for Kids',
    location: 'Jamalkhan, Chattogram',
  },
  {
    id: 'ad-17',
    title: 'Non-stick Cookware Set',
    description: 'A complete set of non-stick cookware. Includes pans, pots, and utensils. Healthy cooking.',
    price: 5500,
    imageUrl: 'https://picsum.photos/seed/ad17/600/400',
    sellerId: 'seller-7',
    category: 'Home Decor',
    location: 'Chawkbazar, Chattogram',
  },
  {
    id: 'ad-18',
    title: 'Professional Football',
    description: 'Official size and weight football. Perfect for practice and matches. High-quality materials.',
    price: 2500,
    imageUrl: 'https://picsum.photos/seed/ad18/600/400',
    sellerId: 'seller-8',
    category: 'Sportswear',
    location: 'M. A. Aziz Stadium, Chattogram',
  },
  {
    id: 'ad-19',
    title: 'Indoor Plant with Pot',
    description: 'Beautiful indoor plant to decorate your home or office. Comes with a ceramic pot.',
    price: 1200,
    imageUrl: 'https://picsum.photos/seed/ad19/600/400',
    sellerId: 'seller-9',
    category: 'Home Decor',
    location: 'Foy\'s Lake, Chattogram',
  },
  {
    id: 'ad-20',
    title: 'Cute Puppy for Adoption',
    description: 'Adorable and healthy puppy looking for a loving home. Vaccinated and dewormed.',
    price: 5000,
    imageUrl: 'https://picsum.photos/seed/ad20/600/400',
    sellerId: 'seller-10',
    category: 'Pets',
    location: 'Nasirabad, Chattogram',
  },
  {
    id: 'ad-21',
    title: 'Office Desk Lamp',
    description: 'Modern and sleek desk lamp with adjustable brightness. Perfect for your workspace.',
    price: 1800,
    imageUrl: 'https://picsum.photos/seed/ad21/600/400',
    sellerId: 'seller-1',
    category: 'Electronics',
    location: 'GEC Circle, Chattogram',
  },
  {
    id: 'ad-22',
    title: 'Men\'s Formal Shoes',
    description: 'Elegant formal shoes for men. Made from genuine leather. Perfect for office or parties.',
    price: 3800,
    imageUrl: 'https://picsum.photos/seed/ad22/600/400',
    sellerId: 'seller-2',
    category: 'Men\'s Shoes',
    location: 'Agrabad, Chattogram',
  },
  {
    id: 'ad-23',
    title: 'Dining Table Set',
    description: '6-seater dining table set. Made from solid wood. Modern design and comfortable chairs.',
    price: 45000,
    imageUrl: 'https://picsum.photos/seed/ad23/600/400',
    sellerId: 'seller-3',
    category: 'Dining Sets',
    location: 'Hathazari, Chattogram',
  },
  {
    id: 'ad-24',
    title: 'Portable Power Bank',
    description: '20000mAh power bank with fast charging support. Charge your devices on the go.',
    price: 2500,
    imageUrl: 'https://picsum.photos/seed/ad24/600/400',
    sellerId: 'seller-4',
    category: 'Gadgets for Men',
    location: 'Patiya, Chattogram',
  },
  {
    id: 'ad-25',
    title: 'Organic Honey (500g)',
    description: 'Pure and organic honey, directly from the Sundarbans. Rich in taste and health benefits.',
    price: 750,
    imageUrl: 'https://picsum.photos/seed/ad25/600/400',
    sellerId: 'seller-5',
    category: 'Grocery Corner',
    location: 'Boalkhali, Chattogram',
  },
  {
    id: 'ad-26',
    title: 'Kids\' Story Book Set',
    description: 'A set of 10 beautifully illustrated story books for kids. Fun and educational.',
    price: 1500,
    imageUrl: 'https://picsum.photos/seed/ad26/600/400',
    sellerId: 'seller-6',
    category: 'Books for Kids',
    location: 'Jamalkhan, Chattogram',
  },
  {
    id: 'ad-27',
    title: 'Blender and Grinder',
    description: 'High-performance blender and grinder. Make smoothies, juices, and grind spices with ease.',
    price: 4800,
    imageUrl: 'https://picsum.photos/seed/ad27/600/400',
    sellerId: 'seller-7',
    category: 'Home Decor',
    location: 'Chawkbazar, Chattogram',
  },
  {
    id: 'ad-28',
    title: 'Cricket Bat',
    description: 'Professional cricket bat made from Kashmir willow. Perfect for leather ball cricket.',
    price: 3500,
    imageUrl: 'https://picsum.photos/seed/ad28/600/400',
    sellerId: 'seller-8',
    category: 'Sportswear',
    location: 'M. A. Aziz Stadium, Chattogram',
  },
  {
    id: 'ad-29',
    title: 'Rose Plant Sapling',
    description: 'A healthy rose plant sapling. Will bloom beautiful red roses. Perfect for your garden.',
    price: 350,
    imageUrl: 'https://picsum.photos/seed/ad29/600/400',
    sellerId: 'seller-9',
    category: 'Home Decor',
    location: 'Foy\'s Lake, Chattogram',
  },
  {
    id: 'ad-30',
    title: 'Persian Cat',
    description: 'A beautiful and playful Persian cat. Well-trained and friendly. Looking for a new home.',
    price: 15000,
    imageUrl: 'https://picsum.photos/seed/ad30/600/400',
    sellerId: 'seller-10',
    category: 'Pets',
    location: 'Nasirabad, Chattogram',
  },
];

export function getAds(): Ad[] {
  return ads;
}

export function getAdById(id: string): Ad | undefined {
  return ads.find(ad => ad.id === id);
}

export function getSellerById(id: string): Seller | undefined {
  return sellers.find(seller => seller.id === id);
}

export function getAdsBySellerId(sellerId: string): Ad[] {
  return ads.filter(ad => ad.sellerId === sellerId);
}
